#!/usr/bin/env python3
"""
Stream Deck Profile Writer MCP Server

Writes directly to the Elgato Stream Deck desktop app profile manifests instead
of taking exclusive USB control of the hardware.
"""

from __future__ import annotations

import asyncio
import json
import logging
from typing import Any

from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp.types import TextContent, Tool

from profile_manager import (
    PageNotFoundError,
    ProfileManager,
    ProfileManagerError,
    ProfileNotFoundError,
    ProfileValidationError,
)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger("streamdeck-profile-mcp")

manager = ProfileManager()
server = Server("streamdeck-profile-mcp")


@server.list_tools()
async def list_tools() -> list[Tool]:
    """List available profile writer tools."""

    button_schema = {
        "type": "object",
        "properties": {
            "key": {
                "type": "integer",
                "description": "Linear button index (0-based, left-to-right, top-to-bottom).",
            },
            "position": {
                "type": "string",
                "description": (
                    "Native position string 'col,row'. "
                    "Use this when you already know the grid slot."
                ),
            },
            "title": {
                "type": "string",
                "description": "Button title to write into the first active state.",
            },
            "icon_path": {
                "type": "string",
                "description": (
                    "Path to a local icon file. PNG is preferred; other formats are converted."
                ),
            },
            "path": {
                "type": "string",
                "description": (
                    "Convenience field for Open actions. "
                    "Usually a script generated by streamdeck_create_action."
                ),
            },
            "action_type": {
                "type": "string",
                "description": "Convenience action type: 'next_page' or 'previous_page'.",
            },
            "action": {
                "type": "object",
                "description": "Full native Stream Deck action object to write at this position.",
            },
            "plugin_uuid": {
                "type": "string",
                "description": (
                    "For advanced actions, the plugin UUID used "
                    "when building a native action object."
                ),
            },
            "plugin_name": {
                "type": "string",
            },
            "plugin_version": {
                "type": "string",
            },
            "action_uuid": {
                "type": "string",
                "description": (
                    "For advanced actions, the native action UUID, "
                    "for example com.elgato.streamdeck.page.next."
                ),
            },
            "action_name": {
                "type": "string",
            },
            "settings": {
                "type": "object",
                "description": "Native action settings object.",
            },
            "state": {
                "type": "integer",
            },
            "font_size": {
                "type": "integer",
            },
            "title_color": {
                "type": "string",
                "description": "Hex color for the title, for example #ffffff.",
            },
            "title_alignment": {
                "type": "string",
                "description": "Title placement such as top or bottom.",
            },
            "show_title": {
                "type": "boolean",
            },
        },
    }

    return [
        Tool(
            name="streamdeck_read_profiles",
            description=(
                "List Stream Deck desktop profiles from the active "
                "ProfilesV3 or ProfilesV2 directory."
            ),
            inputSchema={
                "type": "object",
                "properties": {},
            },
        ),
        Tool(
            name="streamdeck_read_page",
            description="Read a profile page by profile name or ID and page index or directory ID.",
            inputSchema={
                "type": "object",
                "properties": {
                    "profile_name": {
                        "type": "string",
                        "description": "Exact profile name as shown in the Elgato app.",
                    },
                    "profile_id": {
                        "type": "string",
                        "description": (
                            "Directory-based profile ID, usually the "
                            ".sdProfile folder name without the suffix."
                        ),
                    },
                    "page_index": {
                        "type": "integer",
                        "description": "Zero-based page index from streamdeck_read_profiles.",
                    },
                    "directory_id": {
                        "type": "string",
                        "description": (
                            "Page directory ID from streamdeck_read_profiles. "
                            "This is the safest target for updates."
                        ),
                    },
                },
            },
        ),
        Tool(
            name="streamdeck_write_page",
            description=(
                "Create a new page or replace/update an existing Stream Deck desktop page manifest."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "profile_name": {"type": "string"},
                    "profile_id": {"type": "string"},
                    "page_index": {"type": "integer"},
                    "directory_id": {"type": "string"},
                    "page_name": {
                        "type": "string",
                        "description": "Optional page name stored in the page manifest.",
                    },
                    "buttons": {
                        "type": "array",
                        "items": button_schema,
                        "description": (
                            "Buttons to write. Use streamdeck_create_action "
                            "to build Open or script-backed actions."
                        ),
                    },
                    "clear_existing": {
                        "type": "boolean",
                        "description": (
                            "If true, replace the page contents with the "
                            "provided buttons. Defaults to true."
                        ),
                    },
                    "create_new": {
                        "type": "boolean",
                        "description": "Create a new page instead of updating an existing one.",
                    },
                    "make_current": {
                        "type": "boolean",
                        "description": (
                            "When true, make the page the active current page after writing."
                        ),
                    },
                },
            },
        ),
        Tool(
            name="streamdeck_create_icon",
            description=(
                "Generate a 72x72 PNG icon with centered text and colors, "
                "then return its filesystem path."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "text": {"type": "string"},
                    "bg_color": {"type": "string"},
                    "text_color": {"type": "string"},
                    "font_size": {"type": "integer"},
                    "filename": {"type": "string"},
                },
                "required": ["text"],
            },
        ),
        Tool(
            name="streamdeck_create_action",
            description=(
                "Create an executable shell script in ~/StreamDeckScripts "
                "and return a native Open action block for it."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": (
                            "Human-readable action name used for the "
                            "script filename and button label."
                        ),
                    },
                    "command": {
                        "type": "string",
                        "description": "Shell command to run when the button is pressed.",
                    },
                    "working_directory": {
                        "type": "string",
                        "description": (
                            "Optional working directory to cd into before executing the command."
                        ),
                    },
                    "filename": {
                        "type": "string",
                        "description": "Optional override for the script filename.",
                    },
                },
                "required": ["name", "command"],
            },
        ),
        Tool(
            name="streamdeck_restart_app",
            description="Restart the macOS Stream Deck desktop app after profile changes.",
            inputSchema={
                "type": "object",
                "properties": {},
            },
        ),
    ]


@server.call_tool()
async def call_tool(name: str, arguments: dict[str, Any]) -> list[TextContent]:
    """Handle profile writer tool calls."""

    try:
        if name == "streamdeck_read_profiles":
            profiles = manager.list_profiles()
            return [TextContent(type="text", text=json.dumps(profiles, indent=2))]

        if name == "streamdeck_read_page":
            payload = manager.read_page(
                profile_name=arguments.get("profile_name"),
                profile_id=arguments.get("profile_id"),
                page_index=arguments.get("page_index"),
                directory_id=arguments.get("directory_id"),
            )
            return [TextContent(type="text", text=json.dumps(payload, indent=2))]

        if name == "streamdeck_write_page":
            result = manager.write_page(
                profile_name=arguments.get("profile_name"),
                profile_id=arguments.get("profile_id"),
                page_index=arguments.get("page_index"),
                directory_id=arguments.get("directory_id"),
                page_name=arguments.get("page_name"),
                buttons=arguments.get("buttons"),
                clear_existing=arguments.get("clear_existing", True),
                create_new=arguments.get("create_new", False),
                make_current=arguments.get("make_current", False),
            )
            return [TextContent(type="text", text=json.dumps(result, indent=2))]

        if name == "streamdeck_create_icon":
            result = manager.create_icon(
                text=arguments["text"],
                bg_color=arguments.get("bg_color", "#000000"),
                text_color=arguments.get("text_color", "#ffffff"),
                font_size=arguments.get("font_size", 18),
                filename=arguments.get("filename"),
            )
            return [TextContent(type="text", text=json.dumps(result, indent=2))]

        if name == "streamdeck_create_action":
            result = manager.create_action(
                name=arguments["name"],
                command=arguments["command"],
                working_directory=arguments.get("working_directory"),
                filename=arguments.get("filename"),
            )
            return [TextContent(type="text", text=json.dumps(result, indent=2))]

        if name == "streamdeck_restart_app":
            result = manager.restart_app()
            return [TextContent(type="text", text=json.dumps(result, indent=2))]

        return [TextContent(type="text", text=f"❌ Unknown tool: {name}")]

    except (
        ProfileManagerError,
        ProfileNotFoundError,
        PageNotFoundError,
        ProfileValidationError,
    ) as exc:
        return [TextContent(type="text", text=f"❌ {exc}")]
    except Exception as exc:  # pragma: no cover
        logger.exception("Unexpected error in %s", name)
        return [TextContent(type="text", text=f"❌ Unexpected error: {exc}")]


async def main() -> None:
    """Run the profile writer MCP server."""

    logger.info("Starting Stream Deck Profile Writer MCP server")
    async with stdio_server() as (read_stream, write_stream):
        await server.run(read_stream, write_stream, server.create_initialization_options())


def run() -> None:
    """Synchronous wrapper for package entrypoints."""

    asyncio.run(main())


if __name__ == "__main__":
    run()
